# Generated by Django 2.0.2 on 2018-04-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
