# Generated by Django 2.0.2 on 2018-04-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_tracker', '0004_auto_20180424_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
